---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: cloudnative-pg-push
  namespace: rook-ceph
spec:
  updatePolicy: Replace
  refreshInterval: 1m
  secretStoreRefs:
    - name: bitwarden-secrets-manager
      kind: ClusterSecretStore
  selector:
    secret:
      name: cloudnative-pg
  template:
    data:
      # Compose a JSON value from the OBC credentials
      cloudnative-pg-s3-json: |
        {"ACCESS_KEY":"{{ index . "AWS_ACCESS_KEY_ID" }}","SECRET_KEY":"{{ index . "AWS_SECRET_ACCESS_KEY" }}"}
  data:
    - match:
        secretKey: cloudnative-pg-s3-json
        remoteRef:
          remoteKey: cloudnative-pg-s3
