apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./objectstore-user.yaml
  - ./buckets.yaml
  - ./volsync-push-secret.yaml
  - ./cloudnative-pg-push-secret.yaml
