---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: volsync-backups-push
  namespace: rook-ceph
spec:
  updatePolicy: Replace
  refreshInterval: 1m
  secretStoreRefs:
    - name: bitwarden-secrets-manager
      kind: ClusterSecretStore
  selector:
    secret:
      name: volsync-backups
  template:
    data:
      # Compose a JSON value from the OBC credentials + static password
      volsync-kopia-json: |
        {"PASSWORD":"remake-quotation-steed-concave","ACCESS_KEY":"{{ index . "AWS_ACCESS_KEY_ID" }}","SECRET_KEY":"{{ index . "AWS_SECRET_ACCESS_KEY" }}"}
  data:
    - match:
        secretKey: volsync-kopia-json
        remoteRef:
          remoteKey: volsync-kopia
