---
# Automatically apply all upgrade Plans
# Control plane Plans use 'after:' dependency to wait for workers
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-upgrade-plans
  namespace: flux-system
spec:
  targetNamespace: system-upgrade
  commonMetadata:
    labels:
      app.kubernetes.io/managed-by: flux
  dependsOn:
    - name: system-upgrade-controller
  path: ./kubernetes/apps/system-upgrade/plans
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false  # Don't wait - upgrades take time
  interval: 10m
  retryInterval: 2m
  timeout: 1h
