apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  # - ./scrapeconfig.yaml
  - ../../../../templates/gatus/guarded
configMapGenerator:
  - name: kube-prometheus-stack-gatus-ep
    behavior: merge
    literals:
      - NAMESPACE=observability
      - GATUS_PORT=9090
      - GATUS_PATH=/-/healthy
