---
apiVersion: v1
kind: Service
metadata:
  name: k8s-gateway-metrics
  labels:
    app.kubernetes.io/name: k8s-gateway
    app.kubernetes.io/instance: k8s-gateway
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9153
      targetPort: 9153
      protocol: TCP
  selector:
    app.kubernetes.io/name: k8s-gateway
    app.kubernetes.io/instance: k8s-gateway
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k8s-gateway
  labels:
    app.kubernetes.io/name: k8s-gateway
    app.kubernetes.io/instance: k8s-gateway
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: k8s-gateway
      app.kubernetes.io/instance: k8s-gateway
  endpoints:
    - port: metrics
      interval: 1m
      scrapeTimeout: 10s
      path: /metrics
