apiVersion: v1
kind: ConfigMap
metadata:
  name: overseerr-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: overseerr
        group: external
        url: https://overseerr.${SECRET_DOMAIN}/api/v1/status
        interval: 1m
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 200"
          - "[RESPONSE_TIME] < 10000"
        alerts:
          - type: pushover
