apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name sosse-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        SOSSE_DB_NAME: &dbName sosse
        SOSSE_DB_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        SOSSE_DB_PORT: "5432"
        SOSSE_DB_PASS: &dbPass "{{ .SOSSE_POSTGRES_PASSWORD }}"
        SOSSE_DB_USER: &dbUser "{{ .SOSSE_POSTGRES_USER }}"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPERUSER_PASSWORD }}"
        SOSSE_SECRET_KEY: "{{ .SOSSE_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: sosse
    - extract:
        key: POSTGRES
