---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: karakeep-secret
    template:
      engineVersion: v2
      data:
        NEXTAUTH_SECRET: "{{ .NEXTAUTH_SECRET }}"
        OPENAI_API_KEY: "{{ .OPENAI_API_KEY | default \"\" }}"
        MEILI_MASTER_KEY: "{{ .MEILI_MASTER_KEY | default \"\" }}"
  dataFrom:
    - extract:
        key: karakeep
