---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: karakeep
  namespace: flux-system
spec:
  interval: 12h
  url: oci://ghcr.io/karakeep-app/helm-charts/karakeep
  ref:
    tag: 0.27.0
