apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ../../../../templates/gatus/guarded
configMapGenerator:
  - name: grafana-gatus-ep
    behavior: merge
    literals:
      - NAMESPACE=observability
      - GATUS_PORT=80
      - GATUS_PATH=/api/health
