apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./helmrelease.yaml
  - ../../../../templates/gatus/guarded
  - ../../../../templates/volsync
configMapGenerator:
  - name: unifi-gatus-ep
    literals:
      - NAMESPACE=default
      - GATUS_URL=https://unifi.default.svc.cluster.local:8443/status
      - GATUS_STATUS=200
