apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  # Removed: convertx, manyfold, sosse, spoolman (unused apps)
  - ./dahua-companion/ks.yaml
  - ./frigate/ks.yaml
  - ./go2rtc/ks.yaml
  - ./home-assistant/ks.yaml
  - ./homebox/ks.yaml
  - ./homepage/ks.yaml
  - ./karakeep/ks.yaml
  - ./mealie/ks.yaml
  - ./paperless/ks.yaml
  - ./stirling-pdf/ks.yaml
  - ./unifi/ks.yaml
  - ./zigbee2mqtt/ks.yaml
