apiVerdata:
  config.yaml: |
    endpoints:
      - name: bazarr
        group: guarded
        url: http://bazarr.media.svc.cluster.local:80/
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        conditions:
          - "[STATUS] == 200"
          - "[RESPONSE_TIME] < 5000"
        alerts:
          - type: pushoverConfigMap
metadata:
  name: bazarr-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: bazarr
        group: guarded
        url: http://bazarr.media.svc.cluster.local:6767/api/system/health
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        conditions:
          - "[STATUS] == 200"
          - "[RESPONSE_TIME] < 5000"
        alerts:
          - type: pushover
