---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opnsense-exporter-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: opnsense-exporter-secret
    template:
      engineVersion: v2
      data:
        OPNSENSE_API_KEY: "{{ .OPNSENSE_API_KEY }}"
        OPNSENSE_API_SECRET: "{{ .OPNSENSE_API_SECRET }}"
  dataFrom:
    - extract:
        key: opnsense
