web:
  port: ${WEB_PORT}
storage:
  type: postgres
  path: postgres://${INIT_POSTGRES_USER}:${INIT_POSTGRES_PASS}@${INIT_POSTGRES_HOST}:5432/${INIT_POSTGRES_DBNAME}?sslmode=disable
  caching: true
metrics: true
debug: false
ui:
  title: Status | Gatus
  header: Status
# alerting:
#   pushover:
#     title: Gatus
#     application-token: ${PUSHOVER_TOKEN}
#     user-key: ${PUSHOVER_USER_KEY}
#     priority: 1
#     default-alert:
#       description: health-check failed
#       send-on-resolved: true
#       failure-threshold: 3
#       success-threshold: 3
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m
endpoints:
  - name: flux-webhook
    group: external
    url: https://flux-webhook.${SECRET_DOMAIN}
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 404"
    alerts:
      - type: pushover

  - name: rook-ceph-dashboard
    group: infrastructure
    url: https://rook.${SECRET_DOMAIN}
    interval: 2m
    client:
      dns-resolver: tcp://192.168.5.2:53
      insecure: true
      timeout: 10s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 5000"
    alerts:
      - type: pushover

  - name: ceph-object-gateway
    group: infrastructure
    url: https://rgw.${SECRET_DOMAIN}
    interval: 2m
    client:
      dns-resolver: tcp://192.168.5.2:53
      insecure: true
      timeout: 10s
    conditions:
      - "[STATUS] == any(200, 404)"
      - "[RESPONSE_TIME] < 5000"
    alerts:
      - type: pushover

  - name: grafana
    group: observability
    url: https://grafana.${SECRET_DOMAIN}
    interval: 2m
    client:
      dns-resolver: tcp://192.168.5.2:53
      insecure: true
      timeout: 10s
    conditions:
      - "[STATUS] == any(200, 302)"
      - "[RESPONSE_TIME] < 5000"
    alerts:
      - type: pushover

  - name: prometheus
    group: observability
    url: https://prometheus.${SECRET_DOMAIN}
    interval: 2m
    client:
      dns-resolver: tcp://192.168.5.2:53
      insecure: true
      timeout: 10s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 5000"
    alerts:
      - type: pushover
