---
apiVersion: v1
data:
  ADGUARD_IP: 192.168.5.2
  EMQX_LB: 192.168.5.21
  GO2RTC_LB: 192.168.5.22
  NAS_IP: 192.168.5.10
  POSTGRES_LB: 192.168.5.23
  TIMEZONE: America/Denver
  TORRENTS_LB: 192.168.5.24
  UNIFI_LB: 192.168.5.25
  AMBIENTWEATHER_LB: 192.168.5.26
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
