---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./deployment.yaml
  - ./externalsecret.yaml
configMapGenerator:
  - name: notifier-scripts
    files:
      - resources/sonarr-pushover.sh
      - resources/radarr-pushover.sh
      - resources/jellyseerr-pushover.sh
generatorOptions:
  disableNameSuffixHash: true
