---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name paperless-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # Database
        POSTGRES_DB: &dbName paperless
        POSTGRES_SERVER: &dbHost postgres16-rw.database.svc.cluster.local
        POSTGRES_PORT: "5432"
        POSTGRES_PASSWORD: &dbPass "{{ .PAPERLESS_POSTGRES_PASSWORD }}"
        POSTGRES_USER: &dbUser "{{ .PAPERLESS_POSTGRES_USER }}"
        # Init Container
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPERUSER_PASSWORD }}"
        # Paperless
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: paperless
    - extract:
        key: POSTGRES
