---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-exporter-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: adguard-exporter-secret
    template:
      engineVersion: v2
      data:
        ADGUARD_USERNAME: "{{ .ADGUARD_USERNAME }}"
        ADGUARD_PASSWORD: "{{ .ADGUARD_PASSWORD }}"
  dataFrom:
    - extract:
        key: adguard
