---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: kopia-bucket-push
  namespace: volsync-system
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: bitwarden-secrets-manager
      kind: ClusterSecretStore
  selector:
    secret:
      name: kopia-bucket
  data:
    - match:
        secretKey: AWS_ACCESS_KEY_ID
        remoteRef:
          remoteKey: volsync-kopia
          property: ACCESS_KEY
    - match:
        secretKey: AWS_SECRET_ACCESS_KEY
        remoteRef:
          remoteKey: volsync-kopia
          property: SECRET_KEY
