apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./configmap.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./rbac.yaml
  - ../../../../templates/gatus/guarded
configMapGenerator:
  - name: homepage-gatus-ep
    behavior: merge
    literals:
      - NAMESPACE=default
      - GATUS_PORT=3000
      - GATUS_PATH=/
