---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-dns
  namespace: network
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: adguard-dns-secret
    template:
      engineVersion: v2
      data:
        ADGUARD_URL: "{{ .ADGUARD_URL }}"
        ADGUARD_USER: "{{ .ADGUARD_USER }}"
        ADGUARD_PASSWORD: "{{ .ADGUARD_PASSWORD }}"
  dataFrom:
    - extract:
        key: adguard
